### ISSUE TITLE
Docker 镜像无法使用

### ISSUE THREAD

**Issue by HoshinoRei** [fantasylidong/AnneZonemod#13]
作者你好，小玲使用 `morzlee/anne` 这个镜像部署，但是却无法正常启动容器。系统是 Debian 11.5，Docker 版本 20.10.18，Docker Compose 版本 2.10.2。

```yml
version: "3"
services:
  anne:
    container_name: anne
    image: morzlee/anne
    environment:
      - PORT=27015
      - MAP=c1m1_hotel
      - REGION=4
      - plugin=anne
    network_mode: host
    restart: unless-stopped
```

日志：

```bash
root@debian:~# sudo docker logs anne
/bin/sh: 1: ./entrypoint.sh: Permission denied
/bin/sh: 1: ./entrypoint.sh: Permission denied
/bin/sh: 1: ./entrypoint.sh: Permission denied
/bin/sh: 1: ./entrypoint.sh: Permission denied
/bin/sh: 1: ./entrypoint.sh: Permission denied
```

另外 `morzlee/anneserver:test` 和 `morzlee/anneserver:stable` 也是一样的情况。
